version: 2.1
jobs:
  build:
    docker:
      - image: citus/extbuilder:latest

    steps:
      - checkout

      - run:
          name: 'build and install'
          command: make install

      - run:
          name: test if installed
          command: pg_autoctl --version