version: 2.1
jobs:
  build:
    docker:
      - image: citus/pgautofailover:pg12

    steps:
      - checkout

      - run:
          name: 'build and install'
          command: make -s && sudo make install

      - run:
          name: test if installed
          command: pg_autoctl --version
      - run:
          name: prepare test
          command: PIPENV_PIPFILE=tests/Pipfile pipenv install --system --deploy
      - run:
          name: run tests
          command: make test
